services:

  backend:
    build: 
      context: ./words-counter-backend
    ports:
      - 8081:8081
    network_mode: bridge
    networks:
      - public

  frontend:
    build:
      context: ./words-counter-frontend
      dockerfile: Dockerfile-dev
    ports:
      - 8000:8000
    depends_on:
      - "backend"
    environment:
      - PORT=8000
      - VUE_APP_SERVER_URL=http://localhost:8081
    network_mode: bridge
    networks:
      - public

networks:
  public:
